import assert from 'node:assert';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { createDocumentationFreeze, loadExportProfile } from '../scripts/core/freeze.js';

function writeFile(filePath: string, content: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}

function createFixture() {
  const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'openlag-freeze-'));

  writeFile(path.join(projectRoot, 'templates', 'freeze', 'freeze-template.html'), [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8" />',
    '<style>.cover{padding:1rem}.artifact-card{border:1px solid #ddd}.footer{font-size:.8rem}</style>',
    '</head>',
    '<body>',
    '<span data-template="cover.title">Template title</span>',
    '<span data-template="executiveSummary.purpose">Template purpose</span>',
    '<main class="document"></main>',
    '</body>',
    '</html>',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'OpenLAG-logo-t.png'), 'not-a-real-png');

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'artifacts', 'PROJECT.yaml'), [
    'type: PROJECT',
    'layer: DOCUMENTATION',
    'description: Project artifact.',
    'requiredFields: [id, type, title, description]',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'artifacts', 'REQUIREMENT.yaml'), [
    'type: REQUIREMENT',
    'layer: BUSINESS',
    'description: Requirement artifact.',
    'requiredFields: [id, type, title, description]',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'artifacts', 'COMPONENT.yaml'), [
    'type: COMPONENT',
    'layer: ARCHITECTURE',
    'description: Component artifact.',
    'requiredFields: [id, type, title, description]',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'relations', 'IMPLEMENTS.yaml'), [
    'relation: IMPLEMENTS',
    'description: Implements a requirement.',
    'category: TRACEABILITY',
    'allowedFrom: [COMPONENT]',
    'allowedTo: [REQUIREMENT]',
    'validation:',
    '  severity: error',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'export-profiles', 'architecture.yaml'), [
    'id: architecture',
    'name: Architecture Freeze',
    'defaultFormat: markdown',
    'template:',
    '  id: professional-document-v1',
    '  path: templates/freeze/freeze-template.html',
    'branding:',
    '  logo: OpenLAG-logo-t.png',
    '  productName: OpenLAG',
    '  subtitle: Documentation Freeze',
    'document:',
    '  language: en',
    '  title: Architecture Freeze',
    '  eyebrow: Generated Architecture Snapshot',
    '  description: Deterministic architecture documentation generated from the current OpenLAG graph.',
    'executiveSummary:',
    '  title: Executive Summary',
    '  purposeTitle: Document purpose',
    '  purpose: propósito frágil evolución contraseña auditoría diseño integración',
    '  scopeTitle: Scope',
    '  scope: The content is selected by the active export profile.',
    '  audienceTitle: Intended audience',
    '  audience: Architecture, governance and engineering teams.',
    'footer:',
    '  left: Generated by OpenLAG freeze',
    '  right: Document template professional-document-v1',
    'includeArtifactTypes: [PROJECT, REQUIREMENT, COMPONENT]',
    'includeRelations: [IMPLEMENTS]',
    'sections:',
    '  - id: overview',
    '    title: Overview',
    '    artifactTypes: [PROJECT]',
    '  - id: requirements',
    '    title: Requirements',
    '    artifactTypes: [REQUIREMENT]',
    '  - id: architecture',
    '    title: Architecture',
    '    artifactTypes: [COMPONENT]',
    'rendering:',
    '  includeCover: true',
    '  includeExecutiveSummary: true',
    '  includeTableOfContents: true',
    '  includeRelationTables: true',
    '  includeSourceMetadata: true',
    '  includeTechnicalMetadata: false',
    '  includeFooter: true',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'requirements', 'req-a.md'), [
    '---',
    'id: req-a',
    'type: REQUIREMENT',
    'title: Alpha Requirement',
    'description: Alpha must exist.',
    'version: v-1',
    'status: ready',
    '---',
    '',
    '# Alpha Requirement',
    '',
    'A requirement with propósito, frágil, evolución, contraseña, auditoría, diseño, integración.',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'architecture', 'cmp-a.md'), [
    '---',
    'id: cmp-a',
    'type: COMPONENT',
    'title: Alpha Component',
    'description: Implements alpha.',
    'version: v-1',
    'status: ready',
    'relations:',
    '  - type: IMPLEMENTS',
    '    to: req-a',
    '---',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'architecture', 'project.md'), [
    '---',
    'id: project-a',
    'type: PROJECT',
    'title: Project Alpha',
    'description: Project summary.',
    'version: v-1',
    'status: ready',
    '---',
    '',
  ].join('\n'));

  return projectRoot;
}

test('loads an export profile from docs/contracts/export-profiles', () => {
  const projectRoot = createFixture();
  const profile = loadExportProfile(projectRoot, 'architecture');

  assert.strictEqual(profile.id, 'architecture');
  assert.strictEqual(profile.sections.length, 3);
  assert.deepStrictEqual(profile.includeRelations, ['IMPLEMENTS']);
});

test('dry-run creates deterministic markdown without writing output', () => {
  const projectRoot = createFixture();
  const first = createDocumentationFreeze({ projectRoot, profile: 'architecture', dryRun: true });
  const second = createDocumentationFreeze({ projectRoot, profile: 'architecture', dryRun: true });

  assert.strictEqual(first.markdown, second.markdown);
  assert.strictEqual(first.dryRun, true);
  assert.strictEqual(fs.existsSync(first.outputFile), false);
  assert.match(first.markdown, /# Architecture Freeze/);
  assert.match(first.markdown, /## Requirements/);
  assert.match(first.markdown, /`IMPLEMENTS`/);
});

test('writes markdown freeze to dist/openlag/exports by default', () => {
  const projectRoot = createFixture();
  const result = createDocumentationFreeze({ projectRoot, profile: 'architecture' });

  assert.strictEqual(
    result.outputFile,
    path.join(projectRoot, 'dist', 'openlag', 'exports', 'architecture', 'openlag-architecture.md')
  );
  assert.strictEqual(fs.existsSync(result.outputFile), true);
  assert.strictEqual(fs.readFileSync(result.outputFile, 'utf-8'), result.markdown);
});

test('renders json, html, and pdf from the same frozen document model', () => {
  const projectRoot = createFixture();
  const json = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'json' });
  const html = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'html' });
  const pdf = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'pdf' });

  assert.match(json.outputFile, /openlag-architecture\.json$/);
  assert.match(html.outputFile, /openlag-architecture\.html$/);
  assert.match(pdf.outputFile, /openlag-architecture\.pdf$/);
  assert.equal(JSON.parse(String(json.content)).formatVersion, 'openlag.freeze.v1');
  assert.match(String(html.content), /<!doctype html>/);
  assert.equal(Buffer.isBuffer(pdf.content), true);
  assert.equal(fs.readFileSync(pdf.outputFile).subarray(0, 5).toString(), '%PDF-');
});

test('renders professional HTML from the freeze template contract', () => {
  const projectRoot = createFixture();
  const html = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'html' });
  const content = String(html.content);

  assert.match(content, /<meta charset="utf-8"/);
  assert.match(content, /class="cover"/);
  assert.match(content, /Executive Summary/);
  assert.match(content, /data:image\/png;base64/);
  assert.match(content, /class="artifact-card"/);
  assert.match(content, /Outgoing relations/);
  assert.match(content, /Incoming relations/);
  assert.match(content, /IMPLEMENTS/);
  assert.match(content, /propósito frágil evolución contraseña auditoría diseño integración/);
  assert.doesNotMatch(content, /data-template=/);
  assert.doesNotMatch(content, /id: req-a\s+type: REQUIREMENT/);
});

test('keeps markdown and json compatibility with extended export profiles', () => {
  const projectRoot = createFixture();
  const markdown = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'markdown' });
  const json = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'json' });
  const parsed = JSON.parse(String(json.content));

  assert.match(markdown.markdown, /# Architecture Freeze/);
  assert.match(markdown.markdown, /## Requirements/);
  assert.strictEqual(parsed.profile.template.id, 'professional-document-v1');
  assert.strictEqual(parsed.profile.branding.productName, 'OpenLAG');
  assert.strictEqual(parsed.profile.rendering.includeTechnicalMetadata, false);
});
