import assert from 'node:assert';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {
  createDocumentationFreeze,
  inlineOfflineTemplateVendors,
  loadExportProfile,
  REQUIRED_TEMPLATE_PLACEHOLDERS,
  REQUIRED_TEMPLATE_SLOTS,
  validateFreezeTemplateSource,
} from '../scripts/core/freeze.js';

function writeFile(filePath: string, content: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}

function createFixture() {
  const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'openlag-freeze-'));

  writeFile(path.join(projectRoot, 'templates', 'freeze', 'freeze-template.html'), [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8" />',
    '<style>.cover{padding:1rem}.artifact-card{border:1px solid #ddd;break-inside:avoid;page-break-inside:avoid}.footer{font-size:.8rem}@media print{.artifact-card{break-inside:avoid;page-break-inside:avoid}}</style>',
    '<script id="openlag-vendor-marked">/* __OPENLAG_INLINE_MARKED_BUNDLE__ */</script>',
    '<script id="openlag-vendor-mermaid">/* __OPENLAG_INLINE_MERMAID_BUNDLE__ */</script>',
    '<script>document.documentElement.dataset.mermaid="ready";</script>',
    '</head>',
    '<body>',
    '<main class="document">',
    '<section class="cover">',
    '<img data-template-src="branding.logo" alt="logo">',
    ...REQUIRED_TEMPLATE_PLACEHOLDERS.map((name) => `<span data-template="${name}">${name}</span>`),
    '</section>',
    ...REQUIRED_TEMPLATE_SLOTS.map((name) => `<div data-slot="${name}"></div>`),
    '</main>',
    '</body>',
    '</html>',
    '',
  ].join('\n'));

  for (const templateName of ['technical-manual.html', 'executive-brief.html', 'audit-dossier.html', 'knowledge-map.html']) {
    writeFile(
      path.join(projectRoot, 'templates', 'freeze', templateName),
      fs.readFileSync(path.join(process.cwd(), 'templates', 'freeze', templateName), 'utf-8')
    );
  }

  writeFile(path.join(projectRoot, 'OpenLAG-logo-t.png'), 'not-a-real-png');

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'artifacts', 'PROJECT.yaml'), [
    'type: PROJECT',
    'layer: DOCUMENTATION',
    'description: Project artifact.',
    'requiredFields: [id, type, title, description]',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'artifacts', 'REQUIREMENT.yaml'), [
    'type: REQUIREMENT',
    'layer: BUSINESS',
    'description: Requirement artifact.',
    'requiredFields: [id, type, title, description]',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'artifacts', 'COMPONENT.yaml'), [
    'type: COMPONENT',
    'layer: ARCHITECTURE',
    'description: Component artifact.',
    'requiredFields: [id, type, title, description]',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'relations', 'IMPLEMENTS.yaml'), [
    'relation: IMPLEMENTS',
    'description: Implements a requirement.',
    'category: TRACEABILITY',
    'allowedFrom: [COMPONENT]',
    'allowedTo: [REQUIREMENT]',
    'validation:',
    '  severity: error',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'contracts', 'export-profiles', 'architecture.yaml'), [
    'id: architecture',
    'name: Architecture Freeze',
    'defaultFormat: markdown',
    'template:',
    '  id: professional-document-v1',
    '  path: templates/freeze/freeze-template.html',
    'branding:',
    '  logo: OpenLAG-logo-t.png',
    '  productName: OpenLAG',
    '  subtitle: Documentation Freeze',
    'document:',
    '  language: en',
    '  title: Architecture Freeze',
    '  eyebrow: Generated Architecture Snapshot',
    '  description: Deterministic architecture documentation generated from the current OpenLAG graph.',
    'executiveSummary:',
    '  title: Executive Summary',
    '  purposeTitle: Document purpose',
    '  purpose: propósito frágil evolución contraseña auditoría diseño integración',
    '  scopeTitle: Scope',
    '  scope: The content is selected by the active export profile.',
    '  audienceTitle: Intended audience',
    '  audience: Architecture, governance and engineering teams.',
    'footer:',
    '  left: Generated by OpenLAG freeze',
    '  right: Document template professional-document-v1',
    'includeArtifactTypes: [PROJECT, REQUIREMENT, COMPONENT]',
    'includeRelations: [IMPLEMENTS]',
    'sections:',
    '  - id: overview',
    '    title: Overview',
    '    artifactTypes: [PROJECT]',
    '  - id: requirements',
    '    title: Requirements',
    '    artifactTypes: [REQUIREMENT]',
    '  - id: architecture',
    '    title: Architecture',
    '    artifactTypes: [COMPONENT]',
    'rendering:',
    '  includeCover: true',
    '  includeExecutiveSummary: true',
    '  includeTableOfContents: true',
    '  includeRelationTables: true',
    '  includeSourceMetadata: true',
    '  includeTechnicalMetadata: false',
    '  includeFooter: true',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'requirements', 'req-a.md'), [
    '---',
    'id: req-a',
    'type: REQUIREMENT',
    'title: Alpha Requirement',
    'description: Alpha must exist.',
    'version: v-1',
    'status: ready',
    '---',
    '',
    '# Alpha Requirement',
    '',
    'A requirement with propósito, frágil, evolución, contraseña, auditoría, diseño, integración.',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'architecture', 'cmp-a.md'), [
    '---',
    'id: cmp-a',
    'type: COMPONENT',
    'title: Alpha Component',
    'description: Implements alpha.',
    'version: v-1',
    'status: ready',
    'relations:',
    '  - type: IMPLEMENTS',
    '    to: req-a',
    '---',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'architecture', 'cmp-b.md'), [
    '---',
    'id: cmp-b',
    'type: COMPONENT',
    'title: Component Without Description',
    'version: v-1',
    'status: ready',
    '---',
    '',
    '# Component Without Description',
    '',
    'This body must not be promoted to the artifact description.',
    '',
  ].join('\n'));

  writeFile(path.join(projectRoot, 'docs', 'architecture', 'project.md'), [
    '---',
    'id: project-a',
    'type: PROJECT',
    'title: Project Alpha',
    'description: Project summary.',
    'version: v-1',
    'status: ready',
    '---',
    '',
  ].join('\n'));

  return projectRoot;
}

test('loads an export profile from docs/contracts/export-profiles', () => {
  const projectRoot = createFixture();
  const profile = loadExportProfile(projectRoot, 'architecture');

  assert.strictEqual(profile.id, 'architecture');
  assert.strictEqual(profile.sections.length, 3);
  assert.deepStrictEqual(profile.includeRelations, ['IMPLEMENTS']);
});

test('dry-run creates deterministic markdown without writing output', () => {
  const projectRoot = createFixture();
  const generatedAt = '2026-05-27T10:00:00.000Z';
  const first = createDocumentationFreeze({ projectRoot, profile: 'architecture', dryRun: true, generatedAt });
  const second = createDocumentationFreeze({ projectRoot, profile: 'architecture', dryRun: true, generatedAt });

  assert.strictEqual(first.markdown, second.markdown);
  assert.strictEqual(first.dryRun, true);
  assert.strictEqual(fs.existsSync(first.outputFile), false);
  assert.match(first.markdown, /# Architecture Freeze/);
  assert.match(first.markdown, /## Requirements/);
  assert.match(first.markdown, /`IMPLEMENTS`/);
});

test('uses a real generation timestamp by default', () => {
  const projectRoot = createFixture();
  const result = createDocumentationFreeze({ projectRoot, profile: 'architecture', dryRun: true });

  assert.notStrictEqual(result.document.generatedAt, '1970-01-01T00:00:00.000Z');
  assert.doesNotMatch(result.markdown, /1970-01-01T00:00:00.000Z/);
});

test('writes markdown freeze to the command directory by default', () => {
  const projectRoot = createFixture();
  const result = createDocumentationFreeze({ projectRoot, profile: 'architecture' });

  assert.strictEqual(
    result.outputFile,
    path.join(projectRoot, 'openlag-architecture.md')
  );
  assert.strictEqual(fs.existsSync(result.outputFile), true);
  assert.strictEqual(fs.readFileSync(result.outputFile, 'utf-8'), result.markdown);
});

test('writes freeze to the explicit output directory when provided', () => {
  const projectRoot = createFixture();
  const result = createDocumentationFreeze({
    projectRoot,
    profile: 'architecture',
    format: 'html',
    template: 'technical-manual',
    output: 'exports',
  });

  assert.strictEqual(
    result.outputFile,
    path.join(projectRoot, 'exports', 'openlag-architecture-technical-manual.html')
  );
  assert.strictEqual(fs.existsSync(result.outputFile), true);
});

test('renders json, html, and pdf from the same frozen document model', () => {
  const projectRoot = createFixture();
  const json = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'json' });
  const html = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'html' });
  const pdf = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'pdf' });

  assert.match(json.outputFile, /openlag-architecture\.json$/);
  assert.match(html.outputFile, /openlag-architecture\.html$/);
  assert.match(pdf.outputFile, /openlag-architecture\.pdf$/);
  assert.equal(JSON.parse(String(json.content)).formatVersion, 'openlag.freeze.v1');
  assert.match(String(html.content), /<!doctype html>/);
  assert.equal(Buffer.isBuffer(pdf.content), true);
  assert.equal(fs.readFileSync(pdf.outputFile).subarray(0, 5).toString(), '%PDF-');
});

test('renders professional HTML from the freeze template contract', () => {
  const projectRoot = createFixture();
  const html = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'html' });
  const content = String(html.content);

  assert.match(content, /<meta charset="utf-8"/);
  assert.match(content, /class="cover"/);
  assert.match(content, /Executive Summary/);
  assert.match(content, /data:image\/png;base64/);
  assert.match(content, /class="artifact-card"/);
  assert.match(content, /id="openlag-vendor-marked"/);
  assert.match(content, /id="openlag-vendor-mermaid"/);
  assert.match(content, /data-openlag-markdown-body/);
  assert.match(content, /Outgoing relations/);
  assert.match(content, /Incoming relations/);
  assert.match(content, /IMPLEMENTS/);
  assert.match(content, /propósito frágil evolución contraseña auditoría diseño integración/);
  assert.doesNotMatch(content, /data-template=/);
  assert.doesNotMatch(content, /id: req-a\s+type: REQUIREMENT/);
  assert.doesNotMatch(content, /<p># Component Without Description/);
});

test('inlines offline vendors in memory without requiring source template mutation', () => {
  const source = [
    '<script id="openlag-vendor-marked">',
    '/* __OPENLAG_INLINE_MARKED_BUNDLE__ */',
    '</script>',
    '<script id="openlag-vendor-mermaid">',
    '/* __OPENLAG_INLINE_MERMAID_BUNDLE__ */',
    '</script>',
  ].join('\n');

  const rendered = inlineOfflineTemplateVendors(source, process.cwd());

  assert.doesNotMatch(rendered, /__OPENLAG_INLINE_MARKED_BUNDLE__/);
  assert.doesNotMatch(rendered, /__OPENLAG_INLINE_MERMAID_BUNDLE__/);
  assert.match(rendered, /OpenLAG inline vendor: marked/);
  assert.match(rendered, /OpenLAG inline vendor: mermaid/);
});

test('bundled freeze templates comply with the shared template contract', () => {
  const templateNames = [
    'freeze-template.html',
    'technical-manual.html',
    'executive-brief.html',
    'audit-dossier.html',
    'knowledge-map.html',
  ];

  for (const templateName of templateNames) {
    const template = fs.readFileSync(path.join(process.cwd(), 'templates', 'freeze', templateName), 'utf-8');
    const validation = validateFreezeTemplateSource(template);

    assert.deepStrictEqual(validation.issues, [], templateName);
    assert.doesNotMatch(template, /OpenLAG inline vendor|marked v\d|__esbuild_esm_mermaid/i);
    assert.match(template, /__OPENLAG_INLINE_MARKED_BUNDLE__/);
    assert.match(template, /__OPENLAG_INLINE_MERMAID_BUNDLE__/);
  }
});

test('all freeze templates preserve documentation coverage from the same model', () => {
  const projectRoot = createFixture();
  const templateNames = ['freeze-template', 'technical-manual', 'executive-brief', 'audit-dossier', 'knowledge-map'];
  const outputs = templateNames.map((templateName) => (
    String(createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'html', template: templateName, dryRun: true }).content)
  ));

  for (const content of outputs) {
    assert.match(content, /project-a/);
    assert.match(content, /req-a/);
    assert.match(content, /cmp-a/);
    assert.match(content, /Overview/);
    assert.match(content, /Requirements/);
    assert.match(content, /Architecture/);
    assert.match(content, /IMPLEMENTS/);
    assert.match(content, /architecture/);
    assert.doesNotMatch(content, /__OPENLAG_INLINE_/);
    assert.match(content, /OpenLAG inline vendor: marked/);
    assert.match(content, /OpenLAG inline vendor: mermaid/);
  }
});

test('keeps markdown and json compatibility with extended export profiles', () => {
  const projectRoot = createFixture();
  const markdown = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'markdown' });
  const json = createDocumentationFreeze({ projectRoot, profile: 'architecture', format: 'json' });
  const parsed = JSON.parse(String(json.content));

  assert.match(markdown.markdown, /# Architecture Freeze/);
  assert.match(markdown.markdown, /## Requirements/);
  assert.strictEqual(parsed.profile.template.id, 'professional-document-v1');
  assert.strictEqual(parsed.profile.branding.productName, 'OpenLAG');
  assert.strictEqual(parsed.profile.rendering.includeTechnicalMetadata, false);
});
