import { LintProfile } from './lint-types.js';

export const defaultProfiles: Record<string, LintProfile> = {
  draft: {
    duplicateId: 'error',
    invalidYaml: 'error',
    brokenRelation: 'error',
    missingRequiredFields: 'info',
    requirementWithoutImplementation: 'info',
    requirementWithoutTest: 'info',
    codeWithoutRequirement: 'info',
    closedArtifactWithPendingRelations: 'info',
    orphanArtifact: 'info',
    invalidRelationType: 'warning',
    invalidArtifactType: 'error',
    invalidLayer: 'info',
    invalidLayerRelation: 'info',
    missingOwnership: 'info',
  },
  feature: {
    duplicateId: 'error',
    invalidYaml: 'error',
    brokenRelation: 'error',
    missingRequiredFields: 'warning',
    requirementWithoutImplementation: 'info',
    requirementWithoutTest: 'info',
    codeWithoutRequirement: 'info',
    closedArtifactWithPendingRelations: 'warning',
    orphanArtifact: 'info',
    invalidRelationType: 'error',
    invalidArtifactType: 'error',
    invalidLayer: 'warning',
    invalidLayerRelation: 'info',
    missingOwnership: 'info',
  },
  develop: {
    duplicateId: 'error',
    invalidYaml: 'error',
    brokenRelation: 'error',
    missingRequiredFields: 'error',
    requirementWithoutImplementation: 'warning',
    requirementWithoutTest: 'warning',
    codeWithoutRequirement: 'warning',
    closedArtifactWithPendingRelations: 'warning',
    orphanArtifact: 'warning',
    invalidRelationType: 'error',
    invalidArtifactType: 'error',
    invalidLayer: 'warning',
    invalidLayerRelation: 'warning',
    missingOwnership: 'warning',
  },
  release: {
    duplicateId: 'error',
    invalidYaml: 'error',
    brokenRelation: 'error',
    missingRequiredFields: 'error',
    requirementWithoutImplementation: 'error',
    requirementWithoutTest: 'error',
    codeWithoutRequirement: 'error',
    closedArtifactWithPendingRelations: 'error',
    orphanArtifact: 'error',
    invalidRelationType: 'error',
    invalidArtifactType: 'error',
    invalidLayer: 'error',
    invalidLayerRelation: 'error',
    missingOwnership: 'error',
  }
};
